# Generated by Django 4.1.7 on 2023-02-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_logo', models.ImageField(null=True, upload_to='logos')),
                ('white_logo', models.ImageField(null=True, upload_to='logos')),
                ('support_contact', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('support_email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('contact_no', models.CharField(max_length=30, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('twitter', models.CharField(max_length=200, null=True)),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('linkedin', models.CharField(max_length=200, null=True)),
                ('pinterest', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
