# Generated by Django 4.1.7 on 2023-02-22 11:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('brief_description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('detail_overview', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('cover_image', models.ImageField(upload_to='course_thumbnail')),
                ('banner_image', models.ImageField(upload_to='course_banner')),
                ('program_level', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
                ('program_start_date', models.DateField(null=True)),
                ('program_end_date', models.DateField(null=True)),
                ('seats', models.IntegerField(null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('is_free', models.IntegerField(blank=True, default=0, null=True)),
                ('is_discounted', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('program_type', models.CharField(choices=[('public', 'Public'), ('regular', 'Regular')], max_length=25, null=True)),
                ('program_duration', models.IntegerField(blank=True, default=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_subscribed', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsCovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50, null=True)),
                ('tools', models.ImageField(default='course-thumbnail.png', upload_to='tools_covered')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsCovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=255, null=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=255, null=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=500, null=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lession_title', models.CharField(max_length=300, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('lession_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document')], max_length=30, null=True)),
                ('video_url', models.FileField(null=True, upload_to='lession')),
                ('summary', models.TextField(null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programsection')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramComplitionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.TextField(blank=True, null=True)),
                ('video_count', models.IntegerField(blank=True, default=0, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='tools_covered',
            field=models.ManyToManyField(to='program.toolscovered'),
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=255)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', models.CharField(max_length=300, null=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
